openapi: 3.1.0
info: 
  title: GitHub Write (ai-shared-memory)
  version: 1.0.0
servers:
  - url: https://api.github.com
components:
  securitySchemes:
    bearerAuth: 
      type: http
      scheme: bearer
security: 
  - bearerAuth: []
paths:
  /repos/{owner}/{repo}/pulls:
    post:
      operationId: createPull
      summary: Create a Pull Request
      parameters:
        - in: path
          name: owner
          required: true
          schema: 
            type: string
        - in: path
          name: repo
          required: true
          schema: 
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [title, head, base]
              properties:
                title: 
                  type: string
                head:  
                  type: string
                  description: 'branch name, e.g. feat/context-patch'
                base:  
                  type: string
                  description: 'target branch, e.g. main'
                body:  
                  type: string
                draft: 
                  type: boolean
      responses:
        '201': 
          description: created
        '422': 
          description: validation failed
  /repos/{owner}/{repo}/issues/{number}/comments:
    post:
      operationId: commentIssue
      summary: Comment on an Issue or PR
      parameters:
        - in: path
          name: owner
          required: true
          schema: 
            type: string
        - in: path
          name: repo
          required: true
          schema: 
            type: string
        - in: path
          name: number
          required: true
          schema: 
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [body]
              properties:
                body: 
                  type: string
      responses:
        '201': 
          description: created
  /repos/{owner}/{repo}/contents/{path}:
    put:
      operationId: upsertContent
      summary: Create or update file contents
      parameters:
        - in: path
          name: owner
          required: true
          schema: 
            type: string
        - in: path
          name: repo
          required: true
          schema: 
            type: string
        - in: path
          name: path
          required: true
          schema: 
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [message, content]
              properties:
                message: 
                  type: string
                content: 
                  type: string
                  description: 'base64-encoded file content'
                branch:  
                  type: string
                sha:     
                  type: string
                  description: 'blob sha when updating'
      responses:
        '200': 
          description: updated
        '201': 
          description: created