name: Auto-merge site/public PRs
on:
  pull_request:
    types: [opened, synchronize, labeled, reopened]
    paths:
      - 'site/public/**'
permissions:
  contents: write
  pull-requests: write
jobs:
  auto_merge:
    if: contains(github.event.pull_request.labels.*.name, 'auto-merge')
    runs-on: ubuntu-latest
    steps:
      - name: Wait for checks to be green
        uses: lewagon/wait-on-check-action@v1.3.3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10
          allowed-conclusions: success
      - name: Merge (squash)
        run: gh pr merge ${{ github.event.pull_request.number }} --squash --auto
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}