name: JSON Lint
on:
  pull_request:
    paths: ['**/*.json']
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate JSON syntax
        run: |
          set -e
          # Finde alle JSON-Dateien und prüfe mit jq
          mapfile -t files < <(git ls-files '*.json')
          for f in "${files[@]}"; do
            echo "Checking $f";
            jq -e . "$f" > /dev/null;
          done