name: Secret Scan

on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ main ]

jobs:
  gitleaks:
    name: Secret Detection
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        with:
          args: '--no-banner --verbose'
          
      - name: Check for hardcoded credentials
        run: |
          echo "Checking for common credential patterns..."
          # Check for common secret patterns
          if grep -rE "(api[_-]?key|apikey|secret|password|passwd|pwd|token|auth)" \
               --include="*.js" --include="*.ts" --include="*.py" --include="*.json" \
               --exclude-dir=node_modules --exclude-dir=.git \
               . | grep -vE "(example|sample|test|mock|placeholder|your[_-]?)" ; then
            echo "⚠️  Warning: Potential secrets detected. Please review."
          else
            echo "✓ No obvious credential patterns found"
          fi